name = "workers-template-lua"
compatibility_date = "2022-06-27"
main = "./dist/worker.mjs"
type = "javascript"
workers_dev = true

#[build]
#command = "yarn build"
#watch_dir = "./index.mjs"
#
#[[rules]]
#type = "CompiledWasm"
#globs = ["module.wasm"]
#
#[[rules]]
#type = "ESModule"
#globs = ["./build/module.js"]
